
POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}
###

//api3
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
###

//api4
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
###

//api5
GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
###

//api6
GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
####

//api7
GET http://localhost:3000/tweets/2/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
###

//api8
GET http://localhost:3000/tweets/5/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
####

//api9
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
###

//api10 post 
POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw
Content-Type: application/json

{
   "tweet": "The Mornings..."
}
###

//api11
DELETE http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjY4NzczODc3fQ.wpVN3pE3BfLwPT-pFHhl1emBbhmAV_sRU0cLoKWxTRw


Content-Type: application/json

{
  "username": "sherlock_holems",
  "password": "sherlocked",
  "name": "Sherlok Holmes",
  "gender": "male"
}

###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username": "sherlock_holems",
  "password": "sherlocked"
}

###
GET  http://localhost:3000/user/tweets/feed/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/user/following/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/user/followers/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/tweets/1/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/tweets/1/likes
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/tweets/3/replies
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

GET  http://localhost:3000/user/tweets
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk

###

POST  http://localhost:3000/user/tweets
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk
Content-Type: application/json

{
    "tweet": "The game Mrs.Hudson is on!"
}

###

DELETE  http://localhost:3000/tweets/19/
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.c2hlcmxvY2tfaG9sZW1z.Nja89z9T43irl2jTQD1zRx1iqUtD2oPHhj5qHjxN2Qk
